<?php

namespace Proxies\__CG__\myBundle\ictBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class scholarship extends \myBundle\ictBundle\Entity\scholarship implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'id', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'schoName', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'schoDetail', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'closingDate', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'state', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'contact', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'url', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'popular');
        }

        return array('__isInitialized__', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'id', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'schoName', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'schoDetail', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'closingDate', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'state', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'contact', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'url', '' . "\0" . 'myBundle\\ictBundle\\Entity\\scholarship' . "\0" . 'popular');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (scholarship $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoName($schoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoName', array($schoName));

        return parent::setSchoName($schoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoName', array());

        return parent::getSchoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoDetail($schoDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoDetail', array($schoDetail));

        return parent::setSchoDetail($schoDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoDetail', array());

        return parent::getSchoDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosingDate($closingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosingDate', array($closingDate));

        return parent::setClosingDate($closingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosingDate', array());

        return parent::getClosingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopular($popular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopular', array($popular));

        return parent::setPopular($popular);
    }

    /**
     * {@inheritDoc}
     */
    public function getPopular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopular', array());

        return parent::getPopular();
    }

}
