<?php

namespace Proxies\__CG__\myBundle\ictBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class activity extends \myBundle\ictBundle\Entity\activity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'id', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'programname', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'programdetail', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'contact', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'duration', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'agegroup', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'gender', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'location', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'eventdates', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'url', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'popular');
        }

        return array('__isInitialized__', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'id', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'programname', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'programdetail', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'contact', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'duration', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'agegroup', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'gender', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'location', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'eventdates', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'url', '' . "\0" . 'myBundle\\ictBundle\\Entity\\activity' . "\0" . 'popular');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (activity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramname($programname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramname', array($programname));

        return parent::setProgramname($programname);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramname', array());

        return parent::getProgramname();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramdetail($programdetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramdetail', array($programdetail));

        return parent::setProgramdetail($programdetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramdetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramdetail', array());

        return parent::getProgramdetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', array($duration));

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', array());

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgegroup($agegroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgegroup', array($agegroup));

        return parent::setAgegroup($agegroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgegroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgegroup', array());

        return parent::getAgegroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventdates($eventdates)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventdates', array($eventdates));

        return parent::setEventdates($eventdates);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventdates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventdates', array());

        return parent::getEventdates();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopular($popular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopular', array($popular));

        return parent::setPopular($popular);
    }

    /**
     * {@inheritDoc}
     */
    public function getPopular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopular', array());

        return parent::getPopular();
    }

}
